### PR TITLE
fix typos "Lorentz" -> "Lorenz"

### PR DESCRIPTION
**Pull request by gabindu**
Lorenz curves are named after Max Otto Lorenz (1876-1959),
see https://en.wikipedia.org/wiki/Max_O._Lorenz

Since some of the files might already be in use, the incorrect filenames
were not changed, just the content.

### CODE REVIEW

**Comment by maharper** [comment]
Excellent.

> Since some of the files might already be in use, the incorrect filenames
> were not changed, just the content.

They do something using redirecting in the OPL ie `bad file name.pg` is only a pointer to `good file name.pg`

I will investigate whether we can do this in the CPL.  If so, we could redirect the bad file names to good file names which would solve the _already in use_ problem. #31

**Comment by gabindu** [comment]
Honestly, I think that leaving "bad" filenames is a minor issue and shouldn't hold up content fixes.  (But investigating #31 for the long term is of course desirable.)

**Comment by maharper** [comment]
@gabindu I should have been more clear.  I wasn't suggesting delaying merging the pull request, just making a note that we could also rename the files later if we could use redirections in the CPL.  The PR looks good to me.

**Comment by mtitcombe** [comment]
Looktz goodtz to me.

**Pull request merged**
